spring:
  thymeleaf:
    mode: HTML5
    cache: false
  datasource:
    url: jdbc:h2:mem:customers;
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none